---
functional:
  - Пользователь имеет возможность зарегистрироваться на сайте
  - Пользователь имеет возможность авторизоваться на  сайте
  - Пользователь может создать игру
  - Пользователь может выбрать язык для решения задачи
  - Пользователь видит код соперника в реальном времени
  - Пользователь может общаться в чате
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Нельзя зарегистрировать повторно один e-mail
  - требование 6
