---
functional:
  - Пользователь имеет возможность зарегистрироваться на сайте
  - Пользователь имеет возможность авторизоваться на  сайте
  - Пользователь может создать игру
  - Пользователь может выбрать язык для решения задачи PHP,Golang,C++,Node.js,Eliksir,Haskell,C#,Dart,Java, Kotlin, Python, Ruby, Rust, TypeScript
  - Пользователь видит код соперника в реальном времени
  - Пользователь может общаться в чате
  - Пользователь может послать ссылку конкретному участнику
  - Пользователь может сдаться
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров Chrome, Mozilla firefox, Opera, Microsoft Edge
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Нельзя зарегистрировать повторно один e-mail
  - Пароль должент содеражать латинские буквы или цифры
  - Пользователь может поробовать игру без авторизации и регистрации
  - Пользователь может восстановить(изменить) пароль
